package com.wyc.core.map;

import com.wyc.entity.User;
import com.wyc.entity.UserExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

@Mapper
public interface UserMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user
   *
   * @mbggenerated Sun Sep 09 20:43:54 GMT+08:00 2018
   */
  @SelectProvider(type = UserSqlProvider.class, method = "countByExample")
  int countByExample(UserExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user
   *
   * @mbggenerated Sun Sep 09 20:43:54 GMT+08:00 2018
   */
  @DeleteProvider(type = UserSqlProvider.class, method = "deleteByExample")
  int deleteByExample(UserExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user
   *
   * @mbggenerated Sun Sep 09 20:43:54 GMT+08:00 2018
   */
  @Delete({"delete from user", "where id = #{id,jdbcType=INTEGER}"})
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user
   *
   * @mbggenerated Sun Sep 09 20:43:54 GMT+08:00 2018
   */
  @Insert({
    "insert into user (id, username, ",
    "password, gmt_create, ",
    "gmt_modified)",
    "values (#{id,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, ",
    "#{password,jdbcType=VARCHAR}, #{gmtCreate,jdbcType=TIMESTAMP}, ",
    "#{gmtModified,jdbcType=TIMESTAMP})"
  })
  int insert(User record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user
   *
   * @mbggenerated Sun Sep 09 20:43:54 GMT+08:00 2018
   */
  @InsertProvider(type = UserSqlProvider.class, method = "insertSelective")
  int insertSelective(User record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user
   *
   * @mbggenerated Sun Sep 09 20:43:54 GMT+08:00 2018
   */
  @SelectProvider(type = UserSqlProvider.class, method = "selectByExample")
  @Results({
    @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
    @Result(column = "username", property = "username", jdbcType = JdbcType.VARCHAR),
    @Result(column = "password", property = "password", jdbcType = JdbcType.VARCHAR),
    @Result(column = "gmt_create", property = "gmtCreate", jdbcType = JdbcType.TIMESTAMP),
    @Result(column = "gmt_modified", property = "gmtModified", jdbcType = JdbcType.TIMESTAMP)
  })
  List<User> selectByExample(UserExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user
   *
   * @mbggenerated Sun Sep 09 20:43:54 GMT+08:00 2018
   */
  @Select({
    "select",
    "id, username, password, gmt_create, gmt_modified",
    "from user",
    "where id = #{id,jdbcType=INTEGER}"
  })
  @Results({
    @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
    @Result(column = "username", property = "username", jdbcType = JdbcType.VARCHAR),
    @Result(column = "password", property = "password", jdbcType = JdbcType.VARCHAR),
    @Result(column = "gmt_create", property = "gmtCreate", jdbcType = JdbcType.TIMESTAMP),
    @Result(column = "gmt_modified", property = "gmtModified", jdbcType = JdbcType.TIMESTAMP)
  })
  User selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user
   *
   * @mbggenerated Sun Sep 09 20:43:54 GMT+08:00 2018
   */
  @UpdateProvider(type = UserSqlProvider.class, method = "updateByExampleSelective")
  int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user
   *
   * @mbggenerated Sun Sep 09 20:43:54 GMT+08:00 2018
   */
  @UpdateProvider(type = UserSqlProvider.class, method = "updateByExample")
  int updateByExample(@Param("record") User record, @Param("example") UserExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user
   *
   * @mbggenerated Sun Sep 09 20:43:54 GMT+08:00 2018
   */
  @UpdateProvider(type = UserSqlProvider.class, method = "updateByPrimaryKeySelective")
  int updateByPrimaryKeySelective(User record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user
   *
   * @mbggenerated Sun Sep 09 20:43:54 GMT+08:00 2018
   */
  @Update({
    "update user",
    "set username = #{username,jdbcType=VARCHAR},",
    "password = #{password,jdbcType=VARCHAR},",
    "gmt_create = #{gmtCreate,jdbcType=TIMESTAMP},",
    "gmt_modified = #{gmtModified,jdbcType=TIMESTAMP}",
    "where id = #{id,jdbcType=INTEGER}"
  })
  int updateByPrimaryKey(User record);
}
