package com.wyc.entity;

import java.util.Date;

public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.id
     *
     * @mbggenerated Mon Sep 10 18:56:06 GMT+08:00 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_name
     *
     * @mbggenerated Mon Sep 10 18:56:06 GMT+08:00 2018
     */
    private String permissionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.gmt_create
     *
     * @mbggenerated Mon Sep 10 18:56:06 GMT+08:00 2018
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.gmt_modified
     *
     * @mbggenerated Mon Sep 10 18:56:06 GMT+08:00 2018
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.id
     *
     * @return the value of permission.id
     *
     * @mbggenerated Mon Sep 10 18:56:06 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.id
     *
     * @param id the value for permission.id
     *
     * @mbggenerated Mon Sep 10 18:56:06 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_name
     *
     * @return the value of permission.permission_name
     *
     * @mbggenerated Mon Sep 10 18:56:06 GMT+08:00 2018
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_name
     *
     * @param permissionName the value for permission.permission_name
     *
     * @mbggenerated Mon Sep 10 18:56:06 GMT+08:00 2018
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.gmt_create
     *
     * @return the value of permission.gmt_create
     *
     * @mbggenerated Mon Sep 10 18:56:06 GMT+08:00 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.gmt_create
     *
     * @param gmtCreate the value for permission.gmt_create
     *
     * @mbggenerated Mon Sep 10 18:56:06 GMT+08:00 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.gmt_modified
     *
     * @return the value of permission.gmt_modified
     *
     * @mbggenerated Mon Sep 10 18:56:06 GMT+08:00 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.gmt_modified
     *
     * @param gmtModified the value for permission.gmt_modified
     *
     * @mbggenerated Mon Sep 10 18:56:06 GMT+08:00 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}